/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:a7b470c1-312d-43d5-85a7-ae01fa404b43",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_cpg1d4aQc",
    "aws_user_pools_web_client_id": "jl474em68riajdcbmh03l4brk",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "ap-south-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "requestTable-dev",
            "region": "ap-south-1"
        },
        {
            "tableName": "volunteerTable-dev",
            "region": "ap-south-1"
        },
        {
            "tableName": "trackData-dev",
            "region": "ap-south-1"
        },
        {
            "tableName": "trackDataCollector-dev",
            "region": "ap-south-1"
        },
        {
            "tableName": "eventQuestions-dev",
            "region": "ap-south-1"
        },
        {
            "tableName": "articleTable-dev",
            "region": "ap-south-1"
        },
        {
            "tableName": "activityTable-dev",
            "region": "ap-south-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "zeshClientApi",
            "endpoint": "https://1ktn95nyg4.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        },
        {
            "name": "connectionWithOtherDB",
            "endpoint": "https://4szlc1ku1g.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        },
        {
            "name": "volunteerRequest",
            "endpoint": "https://rilq5mbkd2.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        },
        {
            "name": "trackApi",
            "endpoint": "https://ya7n65zdj4.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        },
        {
            "name": "eventQuestions",
            "endpoint": "https://zfra1npg2h.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        },
        {
            "name": "articleAPI",
            "endpoint": "https://xbcnk03c1m.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        },
        {
            "name": "activityApi",
            "endpoint": "https://bxj4y1ayx3.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        }
    ]
};


export default awsmobile;
